"""
Kinesis Firehose Data Transformation Lambda
============================================
Called by Firehose for every batch of records before they're written to S3.
We convert JSON → Parquet here for storage/query efficiency.

Firehose contract:
  Input:  { "records": [{ "recordId": str, "data": base64(json_bytes) }] }
  Output: { "records": [{ "recordId": str, "result": "Ok|Dropped|ProcessingFailed",
                           "data": base64(parquet_bytes) }] }

Returning "ProcessingFailed" causes Firehose to send the record to the
error_output_prefix S3 path instead of silently dropping it.
"""

import base64
import io
import json
import logging
import os
from datetime import datetime, timezone
from typing import Any

log = logging.getLogger()
log.setLevel(os.environ.get("LOG_LEVEL", "INFO"))

# Lazy imports — Lambda cold start is faster if we defer heavy imports
# until the first invocation
_pyarrow = None
_pandas = None


def _get_pyarrow():
    global _pyarrow
    if _pyarrow is None:
        import pyarrow as pa
        import pyarrow.parquet as pq
        _pyarrow = (pa, pq)
    return _pyarrow


# Strict schema — enforce types at ingestion time
# Rejecting malformed events here is cheaper than cleaning up bad data downstream
ARROW_SCHEMA = None


def _get_schema():
    global ARROW_SCHEMA
    if ARROW_SCHEMA is None:
        pa, _ = _get_pyarrow()
        ARROW_SCHEMA = pa.schema([
            pa.field("event_id",          pa.string(), nullable=False),
            pa.field("customer_id",        pa.string(), nullable=False),
            pa.field("event_type",         pa.string(), nullable=False),
            pa.field("timestamp",          pa.timestamp("ms", tz="UTC"), nullable=False),
            pa.field("device",             pa.string(), nullable=True),
            pa.field("session_id",         pa.string(), nullable=True),
            pa.field("session_duration",   pa.int32(),  nullable=True),
            pa.field("transaction_amount", pa.float64(), nullable=True),
            # Store feature_flags as JSON string — Athena can parse with json_extract
            pa.field("feature_flags",      pa.string(), nullable=True),
            pa.field("cohort",             pa.string(), nullable=True),
            pa.field("plan",               pa.string(), nullable=True),
            pa.field("customer_state",     pa.string(), nullable=True),
            # Partition columns — Athena uses these for partition pruning
            pa.field("year",   pa.int16(),  nullable=False),
            pa.field("month",  pa.int8(),   nullable=False),
            pa.field("day",    pa.int8(),   nullable=False),
            pa.field("hour",   pa.int8(),   nullable=False),
            # Ingest metadata
            pa.field("_ingest_timestamp",  pa.timestamp("ms", tz="UTC"), nullable=False),
            pa.field("_schema_version",    pa.string(), nullable=True),
        ])
    return ARROW_SCHEMA


def _parse_record(raw_data: bytes) -> dict[str, Any] | None:
    """
    Parse a raw JSON event record.
    Returns None for records that should be silently dropped (e.g., test events).
    Raises ValueError for records that should be flagged as ProcessingFailed.
    """
    try:
        record = json.loads(raw_data.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        raise ValueError(f"Invalid JSON: {e}") from e

    # Required fields — missing any of these is a data quality failure
    required = ["event_id", "customer_id", "event_type", "timestamp"]
    missing = [f for f in required if not record.get(f)]
    if missing:
        raise ValueError(f"Missing required fields: {missing}")

    # Drop synthetic test events generated by CI smoke tests
    if record.get("metadata", {}).get("source") == "smoke-test":
        return None

    # Parse timestamp
    try:
        ts = datetime.fromisoformat(record["timestamp"].replace("Z", "+00:00"))
    except (ValueError, AttributeError) as e:
        raise ValueError(f"Invalid timestamp '{record['timestamp']}': {e}") from e

    now = datetime.now(timezone.utc)
    return {
        "event_id":          str(record["event_id"]),
        "customer_id":       str(record["customer_id"]),
        "event_type":        str(record["event_type"]),
        "timestamp":         ts,
        "device":            record.get("device"),
        "session_id":        record.get("session_id"),
        "session_duration":  int(record["session_duration"]) if record.get("session_duration") is not None else None,
        "transaction_amount": float(record["transaction_amount"]) if record.get("transaction_amount") is not None else None,
        # Serialize nested dict to JSON string for Parquet compatibility
        "feature_flags":     json.dumps(record.get("feature_flags", {})),
        "cohort":            record.get("cohort"),
        "plan":              record.get("plan"),
        "customer_state":    record.get("customer_state"),
        # Partition columns derived from event timestamp
        "year":              ts.year,
        "month":             ts.month,
        "day":               ts.day,
        "hour":              ts.hour,
        "_ingest_timestamp": now,
        "_schema_version":   record.get("metadata", {}).get("schema_version", "1.0"),
    }


def _records_to_parquet(rows: list[dict]) -> bytes:
    """
    Convert a list of parsed event dicts to a Parquet byte buffer.
    Uses SNAPPY compression — good balance of speed vs compression ratio.
    """
    pa, pq = _get_pyarrow()
    schema = _get_schema()

    # Build column arrays
    columns = {field.name: [] for field in schema}
    for row in rows:
        for col in columns:
            columns[col].append(row.get(col))

    # Create Arrow table with strict schema enforcement
    arrays = []
    for field in schema:
        try:
            arr = pa.array(columns[field.name], type=field.type)
        except (pa.ArrowInvalid, pa.ArrowTypeError) as e:
            log.warning(f"Type coercion for column '{field.name}': {e}")
            arr = pa.array(
                [None] * len(columns[field.name]), type=field.type
            )
        arrays.append(arr)

    table = pa.table(arrays, schema=schema)

    # Write to in-memory buffer
    buf = io.BytesIO()
    pq.write_table(
        table,
        buf,
        compression="snappy",
        # Use dictionary encoding for low-cardinality string columns
        # Saves 50-80% space on columns like event_type, device, cohort
        use_dictionary=True,
        write_statistics=True,  # Enables min/max pushdown in Athena
    )
    return buf.getvalue()


def lambda_handler(event: dict, context) -> dict:
    """
    Main Firehose transformation handler.
    Processes records in micro-batches — convert as many as possible,
    mark failures individually so other records in the batch still succeed.
    """
    records_in = event.get("records", [])
    log.info(f"Processing batch of {len(records_in)} records")

    output_records = []
    parsed_rows = []
    record_ids_for_rows = []

    # First pass: parse all records
    for record in records_in:
        record_id = record["recordId"]
        raw_data = base64.b64decode(record["data"])

        try:
            parsed = _parse_record(raw_data)
            if parsed is None:
                # Silently drop test/synthetic records
                output_records.append({
                    "recordId": record_id,
                    "result": "Dropped",
                    "data": record["data"],  # Return original data
                })
            else:
                parsed_rows.append(parsed)
                record_ids_for_rows.append(record_id)

        except ValueError as e:
            log.error(f"Failed to parse record {record_id}: {e}")
            # ProcessingFailed → Firehose writes to error_output_prefix
            output_records.append({
                "recordId": record_id,
                "result": "ProcessingFailed",
                "data": record["data"],
            })

    # Second pass: convert valid records to Parquet in one batch
    # Batching is critical — writing one Parquet file per record would be very slow
    if parsed_rows:
        try:
            parquet_bytes = _records_to_parquet(parsed_rows)
            encoded = base64.b64encode(parquet_bytes).decode("utf-8")

            # All valid records become a single Parquet payload
            # Firehose concatenates these batches into S3 files
            for record_id in record_ids_for_rows:
                output_records.append({
                    "recordId": record_id,
                    "result": "Ok",
                    "data": encoded,
                })

            log.info(
                f"Converted {len(parsed_rows)} records to Parquet "
                f"({len(parquet_bytes):,} bytes)"
            )

        except Exception as e:
            log.error(f"Parquet conversion failed for batch: {e}", exc_info=True)
            # Mark all records in this batch as failed
            for record_id in record_ids_for_rows:
                output_records.append({
                    "recordId": record_id,
                    "result": "ProcessingFailed",
                    "data": "",
                })

    log.info(
        f"Batch complete: "
        f"Ok={sum(1 for r in output_records if r['result']=='Ok')}, "
        f"Dropped={sum(1 for r in output_records if r['result']=='Dropped')}, "
        f"Failed={sum(1 for r in output_records if r['result']=='ProcessingFailed')}"
    )

    return {"records": output_records}
